[package]
name = "rustdiscordbot"
version = "0.1.0"
edition = "2024"

[dependencies]
base64 = "0.22.1"
openssl = "0.10.71"
rand = "0.9.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
